# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_tracker', '0004_auto_20160702_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='amount_in',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='line',
            name='amount_out',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
